name: Create Package

# trigger with tag
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: Run line to check for starting directory path
        run:  pwd && ls
      - name: Setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Setup project secrets
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        if: env.GPR_USER == 'rjsuzuki'
        run: |
          echo "You sir, are qualified."
          touch secrets.properties
          echo gpr.usr=$GPR_USER > secrets.properties
          echo gpr.key=$GPR_API_KEY >> secrets.properties

      - name: Clean, Build, and Publish AAR
        shell: bash
        run: |
          ./gradlew -PciBuild=true clean build
          ./gradlew publish

