name: build_and_publish

# trigger with tag
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run a one-line script
        run: echo 'Hello, friend.'
      - name: Clean, Build, Lint, and Publish AAR
        shell: bash
        env:
            GPR_USER: ${{ env.GPR_USER }}
            GPR_API_KEY: ${{ env.GPR_API_KEY }}
        run: |
          ./gradlew -PciBuild=true clean build
          ./gradlew lint
          ./gradlew publish
