name: build_and_publish

# trigger with tag
on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run a one-line script
        run: echo 'Hello, friend.'
      - name: Setup project secrets
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        if: env.GPR_USER == 'rjsuzuki'
        run: echo "You sir, are qualified."
      - name: Create a placeholder for github.properties file
        run: touch github.properties
      - name: Clean, Build, and Publish AAR
        shell: bash
        run: |
          ./gradlew -PciBuild=true clean build
          ./gradlew publish
        
